name: Github release

on:
    push:
        tags:
            - '[0-9]+.[0-9]+.[0-9]+'

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build and release
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Nodejs
              uses: actions/setup-node@v3
              with:
                  node-version: 20
            - name: NPM Install
              run: npm i
            - name: Production build
              run: npm run build
            - name: Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref_name }}
                  release_name: v${{ github.ref_name }}
                  body: |
                      <!--- RELEASE DRAFT FOR RELASE FROM ${{ github.ref_name }}

                      Checklist:
                      - The release version is correct:
                        - Release tag,
                        - Release name,
                        - Build add name,
                      - The asset ZIP file contains at least and only `manifest.json`, `README.md` and `main.js` files. -->

                      # CHANGELOG - v${{ github.ref_name }}

                      - ...
                  draft: true
                  prerelease: false
            - name: Release assets
              uses: dwenegar/upload-release-assets@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  release_id: ${{ steps.create_release.outputs.id }}
                  assets_path: build
